version: "3.9"
services:
  notebook:
    build: .
    ports:
      - "8888:8888"
      - "8050:8050"
    volumes:
      - ".:/home/notebooks"
  network-api:
    build: ./network-api
    ports:
      - "3000:3000"
